### ISSUE TITLE
The description could be update with default css for .image-container class

### ISSUE THREAD

**Issue by eugenet8k** [gestixi/image-scale#1]
Hey guys,

Thanks for a great component! It worked very well for me, but initially I got confused and I thought it doesn't work at all, because I didn't set the basic minimum of css properties for .image-container class. The most important one is that it's "position:" should be "relative".  I think to avoid this confusion for other people you could update your example with this note. 

Thanks for the great job!

**Comment by nicolasbadia** [comment]
Good point, because the image will be positioned in `absolute` inside of the container, the container must have a position other than `static`.
But the container don't necessary has to be in `relative`. `absolute`and `fixed` work as well.

I gone add a warning if the container is statically positioned, and eventually an option to automatically set it as `relative`.

Thanks for the report.

**Comment by nicolasbadia** [comment]
This has been fixed in version 2.0.
